export default {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
  FECTH_COLLECTIONS: 'FECTH_COLLECTIONS',
  FECTH_COLLECTIONS_PENDING: 'FECTH_COLLECTIONS_PENDING',
  FECTH_COLLECTIONS_FULFILLED: 'FECTH_COLLECTIONS_FULFILLED',
  FECTH_COLLECTIONS_REJECTED: 'FECTH_COLLECTIONS_REJECTED',
};
